### ISSUE TITLE
依存関係またはソースファイルの欠如

### ISSUE THREAD

**Issue by eternalharvest** [ThousandMileEye/eye#32]
# Abstract
クリーンな virtualenv 環境にて `eyed` コマンドの実行ができない。

## How to reproduce
コードベースのルートで以下のコマンドを実行する。

```sh
virtualenv .
source bin/activate
python setup develop.py
eyed
```

### Actual behaviour
* 以下のエラーが出て `eyed` が起動できない
```
Traceback (most recent call last):
  File "/home/takuya/work/eye/bin/eyed", line 11, in <module>
    load_entry_point('eyed', 'console_scripts', 'eyed')()
  File "/home/takuya/work/eye/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/takuya/work/eye/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/home/takuya/work/eye/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/home/takuya/work/eye/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/takuya/work/eye/eyed/__init__.py", line 4, in <module>
    import model
  File "/home/takuya/work/eye/eyed/model/__init__.py", line 6, in <module>
    from log import BACnetSimulationLog, BACnetMeasurementLog
ImportError: No module named log
```
### Expected behaviour

* エラーを伴わず `eyed` が起動できる

**Comment by NaoyaSawada** [comment]
# デバッグ
- モデルの追加漏れへの対応

# 今後
- 機能毎のpull リクエスト体制に変更
